# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    scara_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    gripper_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

joint_state_broadcaster:
  ros__parameters:
    interfaces:
      - position
      - velocity
      - effort
    map_interface_to_joint_state:
      position: position
      velocity: velocity
      effort: effort

scara_controller:
  ros__parameters:
    joints:
      - brazo1_link_joint
      - brazo2_link_joint
      - paloquebaja_link_joint
      - pinza_base_link_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_nonzero_velocity_at_trajectory_end: true
gripper_controller:
  ros__parameters:
    joints:
      - pinza_d_link_joint
      - pinza_i_link_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_nonzero_velocity_at_trajectory_end: true
